spring.config.use-legacy-processing: true

server.port: 7002
server.error.include-message: always

spring:
  application:
    name: recommendation-service

  mongodb:
    embedded:
      version: 5.0.6

  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"
  metrics:
    tags:
      application: ${spring.application.name}

---
spring.profiles: docker

spring.data.mongodb.host: mongodb

server.port: 8080
