spring.config.use-legacy-processing: true
 
server.port: 7001
server.error.include-message: always

spring:
  application:
    name: product-service

  mongodb:
    embedded:
      version: 3.6.5

  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-db

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

management:
  endpoints:  
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}

---
spring.profiles: docker

spring.data.mongodb.host: mongodb

server.port: 8080
