server.port: 7001
server.error.include-message: always

spring:
  mongodb:
    embedded:
      version: 3.6.5

#spring.data.mongodb:
#  host: localhost
#  port: 27017
#  database: product-db

logging:
  level:
    root: INFO
    se.magnus: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

---
spring.profile: docker
server.port: 8080
